# client/Dockerfile.build
FROM node:22-alpine as build

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json (si existe)
COPY /app/package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el contenido del proyecto en el contenedor
COPY . .

# Construye la aplicación Astro en un directorio temporal
RUN npm run build
