# client/Dockerfile.dev
FROM node:22-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json (si existe)
COPY /app/package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el contenido del proyecto en el contenedor
COPY . .

# Expon el puerto de desarrollo de Astro
EXPOSE 4321

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]